// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0gv-I4F5CJwcBV0rlDx-rBM8YdGtUEBw',
    appId: '1:511541638922:web:13917e8866cca65657ecf3',
    messagingSenderId: '511541638922',
    projectId: 'lifeline-vault',
    authDomain: 'lifeline-vault.firebaseapp.com',
    storageBucket: 'lifeline-vault.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmqcihaOrFsARSoV-MSkKNb-jJKxVuJyM',
    appId: '1:511541638922:android:26df493c43ea950f57ecf3',
    messagingSenderId: '511541638922',
    projectId: 'lifeline-vault',
    storageBucket: 'lifeline-vault.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbSUWlFu8HnbAovXkqIhcRJq8cZGeiH0Q',
    appId: '1:511541638922:ios:57639e758954f79857ecf3',
    messagingSenderId: '511541638922',
    projectId: 'lifeline-vault',
    storageBucket: 'lifeline-vault.firebasestorage.app',
    iosBundleId: 'com.zappy.lifeline',
  );

}